### ISSUE TITLE
Fehlende Zauber

### ISSUE THREAD

**Issue by Ineffizienz** [Ineffizienz/Du-nicht-nehmen-Kerze#23]
Für manche Klassen fehlen bestimmte Zauber, die nachträglich hinzugefügt werden müssen.

Duride (Bär):
Growl

Jäger:
Revive Pet

Generell:
First Aid

**Comment by KittyWittyBitty** [comment]
Generell: 
Cooking 

DK: 
Death Gate

**Comment by Synfray** [comment]
Jäger: Tier wiederbeleben
