### ISSUE TITLE
Hunter startet ohne Pet 

### ISSUE THREAD

**Issue by KittyWittyBitty** [Ineffizienz/Du-nicht-nehmen-Kerze#27]
Der Hunter muss sich noch ein Pet zähmen. Idealerweise stellst du pro Familie ein nicht aggressives Tierchen ab (Ferocity/Tenacity/Cunning), also z.B. Raptor/Bär/Schlange. Vermutlich werden die meisten sowieso nur Ferocity nutzen. Hier wären außer Raptor noch möglich: Aasvogel, Katze, Motte, Hyäne, Wespen, Weitschreiter, Wölfe.

**Comment by Ineffizienz** [comment]
Guck mal oben in der Menagerie von Dalaran, da findest du die ganzen Tiere ;)

**Comment by KittyWittyBitty** [comment]
Raptor + Katze wäre super. : )

**Comment by KittyWittyBitty** [comment]
Zufriedenheit auf Maximum setzen, damit man vorher nicht ewig füttern muss. Unzufriedenes Pet macht weniger Schaden (max. 75%).
