### ISSUE TITLE
Händler für Verzauberungen 

### ISSUE THREAD

**Issue by KittyWittyBitty** [Ineffizienz/Du-nicht-nehmen-Kerze#49]
Bisher benötigt: 

- [x] Arcanum of Torment
- [x] Greater Inscription of the Axe
- [x] Greater Speed or Major Agility
- [x] Powerful Stats
- [x] Greater Assault
- [x] Crusher
- [x] Eternal Belt Buckle with Bold Cardinal Ruby
- [x] Icescale Leg Armor
- [x] Tuskarr's Vitality 
- [x] Greater Assault
- [x] Arcanum of the Stalwart Protector
- [x] Greater Inscription of the Pinnacle
- [x] Greater Inscription of the Gladiator
- [x] Fortitude of the Scourge 
- [x] Mighty Armor
- [x] Greater Defense
- [x] Major Stamina
- [x] Glove Reinforcements
- [x] Frosthide Leg Armor

**Comment by Ineffizienz** [comment]
Als erstes bitte einen Händler anlegen und positionieren!

**Comment by Ineffizienz** [comment]
@KittyWittyBitty könntest du da nochmal ein bisschen genauer werden, was du haben möchtest? Ich hab hier drei Einträge bezüglich "Greater Assault" und weiß nicht, welche davon ich einbauen soll :/

**Comment by Synfray** [comment]
Hinzuzufügen:
Aus Schneiderei:

- [ ] 41604 saphirfarbener Zauberfaden
- [ ] 41602 glänzender Zauberfaden
